##**Trabalhando com Diferentes Formatos de Arquivos**

##**1 - Lendo arquivos CSV**

In [ ]:
import pandas as pd

Foi necessário realizar a verificação do arquivo pois ele foi salvo na codificação 'ISO-8859-1' e suas 3 primeiras linhas eram compostas por metadados o que poderia causar um erro na leitura do arquivo.

In [ ]:
file_path = '/content/dados_sus.csv'

try:
    with open(file_path, 'r', encoding='ISO-8859-1') as f:
        for i, line in enumerate(f):
            print(f"Line {i+1}: {line.strip()}")
            if i > 10:
                break
except FileNotFoundError:
    print(f"Error: File not found at {file_path}")
except Exception as e:
    print(f"An error occurred: {e}")

Line 1: Procedimentos hospitalares do SUS - por local de internação - Brasil
Line 2: Valor total por Unidade da Federação e Ano/mês processamento
Line 3: Período:Jan/2008-Mar/2021
Line 4: "Unidade da Federação";"2008/Jan";"2008/Fev";"2008/Mar";"2008/Abr";"2008/Mai";"2008/Jun";"2008/Jul";"2008/Ago";"2008/Set";"2008/Out";"2008/Nov";"2008/Dez";"2009/Jan";"2009/Fev";"2009/Mar";"2009/Abr";"2009/Mai";"2009/Jun";"2009/Jul";"2009/Ago";"2009/Set";"2009/Out";"2009/Nov";"2009/Dez";"2010/Jan";"2010/Fev";"2010/Mar";"2010/Abr";"2010/Mai";"2010/Jun";"2010/Jul";"2010/Ago";"2010/Set";"2010/Out";"2010/Nov";"2010/Dez";"2011/Jan";"2011/Fev";"2011/Mar";"2011/Abr";"2011/Mai";"2011/Jun";"2011/Jul";"2011/Ago";"2011/Set";"2011/Out";"2011/Nov";"2011/Dez";"2012/Jan";"2012/Fev";"2012/Mar";"2012/Abr";"2012/Mai";"2012/Jun";"2012/Jul";"2012/Ago";"2012/Set";"2012/Out";"2012/Nov";"2012/Dez";"2013/Jan";"2013/Fev";"2013/Mar";"2013/Abr";"2013/Mai";"2013/Jun";"2013/Jul";"2013/Ago";"2013/Set";"2013/Out";"2013/Nov";"2013/Dez";"2014/Jan";"2014/Fev";"2014/Mar";"2014/Abr";"2014/Mai";"2014/Jun";"2014/Jul";"2014/Ago";"2014/Set";"2014/Out";"2014/Nov";"2014/Dez";"2015/Jan";"2015/Fev";"2015/Mar";"2015/Abr";"2015/Mai";"2015/Jun";"2015/Jul";"2015/Ago";"2015/Set";"2015/Out";"2015/Nov";"2015/Dez";"2016/Jan";"2016/Fev";"2016/Mar";"2016/Abr";"2016/Mai";"2016/Jun";"2016/Jul";"2016/Ago";"2016/Set";"2016/Out";"2016/Nov";"2016/Dez";"2017/Jan";"2017/Fev";"2017/Mar";"2017/Abr";"2017/Mai";"2017/Jun";"2017/Jul";"2017/Ago";"2017/Set";"2017/Out";"2017/Nov";"2017/Dez";"2018/Jan";"2018/Fev";"2018/Mar";"2018/Abr";"2018/Mai";"2018/Jun";"2018/Jul";"2018/Ago";"2018/Set";"2018/Out";"2018/Nov";"2018/Dez";"2019/Jan";"2019/Fev";"2019/Mar";"2019/Abr";"2019/Mai";"2019/Jun";"2019/Jul";"2019/Ago";"2019/Set";"2019/Out";"2019/Nov";"2019/Dez";"2020/Jan";"2020/Fev";"2020/Mar";"2020/Abr";"2020/Mai";"2020/Jun";"2020/Jul";"2020/Ago";"2020/Set";"2020/Out";"2020/Nov";"2020/Dez";"2021/Jan";"2021/Fev";"2021/Mar";"Total"
Line 5: "Rondônia";1388528,39;2931283,42;1541682,52;1525314,96;1645953,84;1406150,68;3065279,01;3231494,61;3117178,63;3068430,44;2825838,52;2931173,58;2885269,07;2860103,74;3684944,68;3607289,68;3774356,60;3706711,84;3763187,55;3533625,83;3605007,43;3907032,72;3939820,71;3901084,11;3684407,02;3623015,58;3890461,90;4193533,87;4534400,67;4451208,03;4874592,78;4460802,38;5067886,24;4511092,85;4394680,50;4098741,80;4411499,48;3868617,95;4298702,78;5062171,26;4769347,86;4578105,60;4477870,09;5173453,51;5554791,51;4110177,87;4428561,32;3534337,12;4015781,56;4426788,59;4873364,26;4516103,32;4619267,68;5226741,11;4756327,23;4112530,56;4023514,11;3866138,34;3543519,05;3201183,18;4072043,77;4534984,70;5229512,34;5660083,57;5681210,93;5076918,42;5623854,81;5928359,34;6019754,08;6050368,46;6422821,25;6172605,14;5773335,50;6229461,54;6536336,12;6611751,56;7122614,34;7207965,81;6725041,04;7220209,27;6814650,05;5931824,36;6179626,72;6743020,43;7278090,89;6619352,84;7131263,61;6945021,28;7868953,20;7546597,11;8738484,55;6756554,76;7443631,94;6964209,53;6310062,08;6561221,77;7735224,22;7995955,06;7189165,44;7956812,12;7551313,49;7930610,83;8133705,36;8150486,59;8022627,09;7280387,24;7047166,57;6961884,87;7820057,09;6801952,61;7825186,40;8706448,06;7700730,62;7948291,63;8438077,45;7656644,83;8047742,98;8657206,23;8150893,68;7507845,13;7998345,94;8893683,69;8867793,32;8871408,50;8501601,67;8315107,81;8525499,78;9177611,46;7368996,38;8835095,43;8328186,64;8408512,77;9351705,82;8143007,97;8949741,77;9630553,15;9581970,31;7891114,05;9792370,67;9170787,53;8816846,71;10024554,15;9675423,70;8085025,66;9222010,60;7493901,30;8148169,46;7353768,37;7739864,47;9246097,96;11824687,13;11733307,76;10201985,14;7955139,45;9357946,29;8880836,55;9266014,59;7730597,04;11023309,47;996411254,68
Line 6: "Acre";902416,00;1497206,26;1794028,48;1730469,42;1819443,92;1828496,00;2511754,59;2089107,14;2275708,53;1923886,57;1756986,80;2235639,98;2497116,43;2253558,01;2122673,92;2834317,62;2722065,97;2432831,95;2630190,65;2307579,00;-;2826477,02;2170791,18;2541526,44;2491042,33;1954473,90;2389996,38;2654878,60;2844085,21;2336207,19;2125143,06;2430293,67;2377738,44;2184746,84;2468452,90;2516284,54;3051370,08;2629104,42;2485451,79;2685361,47;2723636,56;2703465,22;3136180,38;2779056,81;2843787,04;2678333,12;2995350,62;2798961,10;2477516,55;2020664,45;2891004,20;2917189,18;2856559,74;2972526,32;2642561,57;3092964,63;2305053,90;3023732,28;3077000,68;2652599,99;2629926,82;3042756,88;2938961,84;3078191,21;2690955,41;2484380,90;2695489,86;2858632,12;2747845,31;2787096,33;2833968,00;2817689,19;3401042,72;2727314,78;2876282,12;2997785,18;3048049,52;2842110,36;3186712,81;3061644,48;3008496,43;3162186,27;3185054,44;2542641,25;3375217,14;3024505,16;3102975,42;3080946,80;3065970,28;3179076,68;2849011,25;3238448,07;3279779,27;3010495,38;3054205,54;3001387,94;3049208,63;3351792,42;3118339,30;3378121,43;3168503,68;3916151,76;3837020,05;3659074,22;3540035,67;3184932,00;3019223,73;3264746,69;2821087,89;3361575,80;3080444,99;2792505,42;3268651,85;2397512,85;2348760,00;3139155,41;2765062,92;4540084,78;4120228,96;2610454,55;3576595,19;2444567,37;2602434,35;3064163,42;2276236,69;3239474,10;3126429,88;2998865,51;2619709,86;3018048,94;3342614,24;2123426,26;2664654,52;1906429,95;3096439,63;2411628,00;2840630,58;3260153,59;3250722,84;3204998,88;3052745,65;3124802,29;3021521,75;2874871,28;3331803,55;3417691,07;3076003,20;2286642,60;2896340,24;3045245,80;3915193,20;3640142,82;3391242,21;4044321,44;3276590,10;3696997,31;3715723,12;3538427,92;4077045,92;450048530,47
Line 7: "Amazonas";4735529,42;7118990,57;8196635,49;8259378,42;7831399,90;8477273,62;9368858,72;9352532,70;9363099,35;8618318,83;6555549,08;7777645,88;7403068,36;6683346,89;9927781,20;8844511,21;9079035,96;8832894,53;9373395,97;9578326,03;9730634,16;9179252,65;8314648,93;9050439,39;9419460,86;8680178,57;9168055,41;9897901,80;9651362,37;10854599,47;10417122,89;8718347,13;8221592,12;9613977,03;9927574,41;9470661,21;9736750,91;8745259,80;9380112,36;10179342,29;11061892,22;10211426,03;12123214,39;9559769,10;10082882,91;9971934,86;9280038,03;11310448,23;10352439,40;10902583,74;10336630,29;9891098,07;10955256,77;10614256,72;11280206,14;10115473,76;10606064,15;10488989,62;10042561,52;8864038,68;10739446,51;9684212,55;10130504,54;11391815,28;10568514,30;11145486,18;10698375,56;11873036,73;11047897,23;11291971,45;10409535,59;10075788,88;10854399,27;8530242,21;9541806,56;8926365,37;11573335,40;10115769,72;9843473,49;9940875,63;11022062,33;10881666,13;10596831,32;10073869,11;11653868,55;12074530,23;11599144,27;12592492,33;12785467,37;13414600,97;14294033,22;12546727,34;12996512,49;13035233,22;12949248,84;11336880,23;10920318,02;11918470,84;13023926,19;12155273,10;13519252,14;13076793,34;12605307,29;13670157,49;13659651,19;11115915,16;10975042,21;11172130,72;12819877,21;10999828,34;14050412,75;12450515,95;14585552,51;12789637,85;14376990,41;14240071,26;13594647,25;14584288,95;13158724,61;13169660,32;13572263,03;13083081,70;14322305,22;14643340,51;14632208,09;14500521,14;14840533,42;14427620,91;15818964,25;16358462,57;15391163,74;14154362,85;16791397,31;14369987,43;16339024,96;15622910,63;16483166,92;15422243,28;15961988,04;15787896,78;16515441,67;15788848,91;15784686,14;14388606,82;16063450,73;14939977,20;15107056,74;13534657,88;19698748,89;21129394,43;19769460,14;18059931,43;17841015,63;16408315,10;19895617,91;17765167,69;21430289,17;25917134,55;22032176,22;1917247936,05
Line 8: "Roraima";657889,53;777939,31;718688,03;839994,39;862347,96;832440,66;996693,09;894271,18;910424,17;1191770,32;1056218,71;1244339,25;1085679,25;969528,54;1393226,70;1273734,17;1552638,50;1490587,74;1596751,80;1848998,68;1701611,25;1164711,18;1434809,17;1603817,28;1437340,80;1332094,01;1900513,75;1933875,49;1773958,29;1804729,73;1846639,32;1643518,23;1843163,29;1807885,17;1674871,65;1250999,28;1257275,43;1171045,72;1389668,67;1344865,94;1067658,62;1263672,05;1332059,90;1578802,72;1680654,08;1442744,11;1650204,12;1929960,01;1454967,71;1851381,93;2033270,63;2013566,74;2135433,72;1881388,84;1700584,76;1900737,72;1675603,38;1459814,93;1606433,71;1566723,97;1560766,91;1572959,06;1872493,39;1849434,84;1906244,70;2046527,40;2230115,06;1987863,23;1692032,87;1749131,23;1623751,92;1449573,40;1799254,33;1673138,65;1707514,82;1509667,70;1746450,27;1568152,88;1763225,69;1808929,95;1633205,33;1626604,96;1784288,11;1137519,58;1782510,89;2242719,18;1827444,50;2256510,91;1859541,42;1550643,78;1968388,99;2613984,17;2342709,66;2186291,71;2046678,01;1879063,44;1768010,64;1761873,12;1975897,20;2631309,15;2405520,72;2487164,76;3104153,09;2717341,67;2667842,22;2756299,47;2478590,27;2379805,56;2331250,21;2328221,91;2524744,05;2637579,82;2510634,79;2755620,24;2878177,60;2921978,36;2794080,79;2512259,50;2508514,18;2635287,45;2914195,21;2881281,13;2740423,51;2695484,62;2613895,43;3020718,84;2860584,22;2740088,01;2689103,41;2985029,23;2771881,20;2938769,32;2527888,58;2587642,41;1923440,17;2422446,17;2495491,03;2851291,67;3137537,40;3788154,80;3217218,61;3113940,14;3157977,67;3097113,21;3059823,80;2912519,98;2937346,43;2868820,96;2752228,26;3401864,29;3015488,30;2826486,18;2928043,91;3090313,73;3621031,05;3454460,94;3266928,47;3519773,73;3985530,08;328876965,09
Line 9: "Pará";18864744,11;19553758,20;21937342,70;20842829,69;23249952,88;23240687,56;24002223,56;23341218,03;25172261,32;24011712,48;21526303,70;23896804,99;24613320,93;24015940,01;26624310,10;26478979,58;26366401,19;25440701,25;28079331,88;27588522,26;27967969,22;28430631,19;25432419,12;26405862,20;25841889,70;26527192,33;27433129,31;25753868,16;27515463,84;26934203,47;26668195,02;26606749,81;27226660,53;27185706,84;27019994,90;26036033,25;27913374,40;26771060,28;27060396,38;27868879,78;25307476,19;28343034,68;24565538,49;25528460,74;28301294,35;27370964,61;25880407,71;26238490,03;27326329,10;26349845,26;27351755,74;26908659,29;27046198,36;26377422,89;26363477,67;20608795,00;26719283,05;26927163,20;26243631,89;27313748,48;25716468,35;27230611,92;27800745,33;28157962,06;28931084,84;30073494,18;29200573,47;27861583,35;28490038,60;28389416,65;28630467,92;30205302,72;26976831,19;27636018,25;28440495,48;28229650,98;28722845,27;30356126,43;28147550,89;27946764,08;28959611,93;30101037,11;28718375,83;28616330,52;28542136,50;28618366,52;29168223,09;30174783,94;29979937,84;29322659,71;30471017,89;31563922,22;29964621,66;29189794,43;29285733,64;27695852,89;27606572,27;29569770,87;28560310,47;30014919,19;29516894,49;30774513,14;29981379,23;30099178,67;30831386,91;31994665,39;29052732,84;29146575,51;30754370,21;30351043,39;31280430,65;32051882,54;30507852,39;32202265,99;32771002,63;32204013,38;34983747,88;34138970,65;33280643,37;34426413,15;31591185,32;31378879,00;32909877,51;35053278,80;33973133,85;35560757,57;33465172,06;35497371,12;34896020,28;37385364,64;34294171,03;34168505,29;33849909,80;32871717,66;33130995,71;36044319,40;35906526,59;35242306,77;29460144,72;31179893,86;34175218,80;36122298,83;36874442,23;35947766,42;34365985,58;37417579,86;35610330,34;28292446,48;32998806,72;42192745,99;40804126,43;44385715,88;36820249,47;36965931,34;39004315,80;38015145,79;38354682,46;37688314,23;33276392,89;4705309002,29
Line 10: "Amapá";1120973,34;1268740,33;974651,24;1141137,32;866346,18;1440978,95;1426659,48;1475551,38;1651341,43;1866748,58;1426138,18;1696614,53;1665895,54;1719940,00;1750321,77;2052705,19;1915803,55;1787587,54;1763665,03;1746538,99;2034329,78;1839723,26;1882221,29;1712948,71;1849157,17;1605246,04;1525752,37;1572809,36;1653304,86;1685303,78;1773604,15;1662522,64;1811346,65;1654294,56;1958555,54;1984579,56;1928716,67;1725458,50;1703040,74;1849254,15;1877764,70;1824413,77;1958748,33;1648820,20;2008607,15;1735371,53;1765232,33;1984622,25;1731934,33;1736602,27;1877427,40;1810215,83;1934889,49;1940127,06;2065225,89;1997713,00;2029073,53;2003492,09;2086524,25;1984701,05;1873324,52;1699031,94;1772098,19;2052260,55;2105954,30;2312795,29;2167442,71;2087176,35;2017311,99;1966476,53;2067127,94;1980437,55;1930990,93;1873469,06;1805952,31;1992130,63;2274212,55;1635034,56;2240376,26;2128269,35;1931324,11;1963927,38;1791744,72;1786830,89;1609767,42;1441043,63;1702493,39;1837470,82;1901951,16;2048564,82;1905641,81;1833930,69;2104874,14;1983042,85;1871083,38;1813281,56;1714795,55;1569543,74;1668555,78;1753839,47;1897437,54;2003945,53;2094138,46;1949259,95;1880541,13;1751634,91;1779290,66;1853989,34;1875579,06;1799370,10;1665356,48;1702593,70;1897787,14;2050824,29;1881406,55;1940174,73;1923150,03;2036787,91;1876731,42;1716855,56;1836149,63;1954823,32;1882553,32;1781034,49;1821567,42;2120412,72;1910968,09;2453555,40;2652283,29;2637161,32;2139141,93;2654304,54;2549805,60;2294126,19;2511041,32;2746817,21;2648904,75;2117098,07;2388704,49;2905190,27;2145557,83;2455947,45;2310514,38;2296699,42;2333822,65;2310195,65;1842472,54;1705873,64;2065055,35;2009912,57;3253399,45;2946398,44;2416019,23;2203732,04;2218532,26;2566919,60;2802886,34;2817849,31;3188210,98;309860092,59
Line 11: "Tocantins";3441592,69;4985688,85;6205612,60;4984482,09;5511002,46;4927934,22;5445602,28;5413710,38;5596669,50;4658414,01;5252451,80;5523443,70;5791656,63;5814388,89;6273994,59;6762806,93;6575718,57;6423393,40;6349231,85;6490519,50;6542918,14;6420058,63;6149491,80;6075178,19;6411312,84;6403262,51;6698840,55;6905354,41;6864576,47;6876811,94;6732224,34;7110923,00;6644145,62;6861920,56;6553013,61;6450647,82;6695049,17;6735950,07;7285116,46;7077600,27;7276517,85;7204515,82;7111068,57;6398846,69;6671885,21;6668674,99;6818007,56;7326766,19;7349981,38;6906666,50;8295260,11;7404533,57;7394948,64;7879916,82;7270326,59;7568211,84;7011488,83;6801718,91;6216482,98;6435055,37;6437964,96;7918351,20;7745929,88;7603624,90;7985256,31;8309699,73;6975424,96;7450740,84;7079191,03;7954081,13;6804464,16;6860885,77;7450518,49;7543839,51;7386177,85;7106540,44;7226788,09;7008936,76;7123445,53;8010542,13;7947217,21;8058333,55;7498623,81;6075309,60;7017704,11;6607349,96;6598637,99;7197312,63;6163740,83;7275370,04;6987921,76;6243320,96;5831094,19;6271670,32;6464273,87;5569115,04;5452646,99;7002099,24;7526781,90;6714887,59;6775391,70;6237057,69;6757143,54;6766501,09;6343847,41;5564377,89;6647651,04;6245735,72;6041173,17;6185379,91;7066456,44;5722291,45;7017035,58;6392708,38;5837072,54;6608301,60;6155701,19;5104089,76;5441162,74;5200789,02;5341353,03;5361684,48;5913061,01;4617378,68;4662238,24;5664149,36;5328909,25;5473666,63;5152490,73;5272355,92;4873715,59;5321091,08;5791079,68;5881439,69;6593258,41;6684401,50;7143806,13;6136528,26;7118118,28;7607639,98;8498162,91;7181834,26;6467132,92;7210731,09;8098081,50;7024599,22;7210345,19;6391193,66;6707977,77;7424637,88;9155572,36;8390267,72;8729632,49;7770885,66;527840,46;675277,05;419553,49;319160,87;1357751,33;1020028272,64
Line 12: "Maranhão";10723506,39;13559679,41;13985142,36;14809416,46;14505727,38;14908091,32;15784899,40;15195312,89;14951277,75;16072219,28;14016545,04;15792303,93;14782429,14;16842416,53;16681626,41;17735055,55;17466345,31;17459229,54;18021648,34;19332949,68;19722895,51;19277852,57;18634078,27;19117914,42;18906152,18;17540838,45;19741933,29;19445208,55;20174079,39;20368446,35;20361636,95;20566710,40;19061901,55;20690798,08;21028915,80;19417889,95;20078774,98;20448952,89;20679514,26;21210956,43;20711362,63;20133585,72;20093760,87;20561354,00;20823782,57;21443192,85;20624583,38;21018995,06;19910712,45;20903047,82;21470376,33;23206397,57;23485362,14;22450749,87;23435622,79;21805434,82;21798310,07;21141382,25;21023222,79;19537791,98;21450719,20;21364133,12;22461901,45;23228749,74;25240524,07;24358828,55;24958955,03;24967531,41;25163721,77;25079061,93;24644011,47;24811898,90;25074797,96;23578706,77;24379180,43;24561919,83;24500997,60;26362567,92;25424053,10;26273438,74;26724276,68;25224307,37;25527490,63;24173557,53;23007366,00;24593179,79;25983153,20;25551983,98;27394126,13;26762772,42;27211673,48;26732789,79;26929089,25;26298140,28;25549080,29;25527661,43;26264050,26;24711983,48;25658079,48;26215740,88;26625097,16;26868870,97;27245242,67;26354933,71;25975872,16;25534733,58;25483933,05;20546508,53;26153825,19;25915583,50;27895091,69;26808643,39;28064440,72;27699191,35;29321581,70;28974267,39;28210786,25;28352324,75;26858367,06;29435501,73;28524888,88;26351836,62;30050918,58;31077432,22;29485732,67;29359484,98;29441181,87;30255833,42;29645428,53;29310709,37;28462327,93;29606231,79;30641772,18;27369051,19;30399681,09;30406171,44;31437580,62;30094232,34;30724404,59;31712464,35;30923188,40;32025892,76;31013878,74;29659493,42;30324868,50;30018188,06;29309892,09;25256589,20;31356916,21;34868483,11;35473489,49;32219037,29;30077152,72;33200778,47;31942670,33;30783403,58;30738750,31;30924484,99;39663677,48;3871069498,04

###**Parâmetros da função read_csv**

In [ ]:
dados = pd.read_csv('/content/dados_sus.csv', encoding='ISO-8859-1', sep=';', skiprows=3, header=0)
display(dados.head())

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"

In [ ]:
dados

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"
5,Amapá,"1120973,34","1268740,33","974651,24","1141137,32","866346,18","1440978,95","1426659,48","1475551,38","1651341,43",...,"3253399,45","2946398,44","2416019,23","2203732,04","2218532,26","2566919,60","2802886,34","2817849,31","3188210,98","309860092,59"
6,Tocantins,"3441592,69","4985688,85","6205612,60","4984482,09","5511002,46","4927934,22","5445602,28","5413710,38","5596669,50",...,"9155572,36","8390267,72","8729632,49","7770885,66","527840,46","675277,05","419553,49","319160,87","1357751,33","1020028272,64"
7,Maranhão,"10723506,39","13559679,41","13985142,36","14809416,46","14505727,38","14908091,32","15784899,40","15195312,89","14951277,75",...,"35473489,49","32219037,29","30077152,72","33200778,47","31942670,33","30783403,58","30738750,31","30924484,99","39663677,48","3871069498,04"
8,Piauí,"7985142,43","10079928,25","10298372,45","10775976,33","10398360,88","10528253,88","11040107,92","10549176,40","10899198,97",...,"19908573,27","25663537,49","20230782,72","22389215,72","18911604,50","20883972,79","22689390,32","19400269,01","20018325,75","2280888802,74"
9,Ceará,"15539821,90","25735101,55","28724625,75","30676457,06","30604453,47","31272395,18","30925391,36","27851438,72","30362719,90",...,"56019506,33","61719491,69","56625919,77","59074596,33","56916499,66","50849353,22","52078218,88","53171253,41","62079618,54","6591836650,18"
10,Rio Grande do Norte,"5947814,08","9509755,83","10352238,59","10855108,50","11160168,19","10475071,38","11386349,96","10640817,47","11336030,28",...,"26337808,77","27579658,62","27721340,38","26048003,33","24737052,09","23846816,35","28044464,51","26317613,74","23306498,68","2660122027,15"
11,Paraíba,"10723002,45","11386274,47","12053643,87","12653528,76","12215107,11","12256928,49","12755413,77","12872578,37","12558296,11",...,"27294311,05","23288213,79","19480481,07","19988426,94","18418075,59","18099514,43","19524543,63","21302722,77","25750897,89","2614919044,63"
12,Pernambuco,"14393949,89","24181400,95","29991302,71","34806197,97","32147987,35","32239094,89","32685640,76","35457038,66","33668261,46",...,"74914677,43","77232881,01","71715677,42","66555628,25","78904176,21","70978052,15","83846222,44","75562664,69","83870992,73","8581189975,91"
13,Alagoas,"6243726,32","8376622,16","8408336,22","9090794,82","9338771,45","10068210,08","9887061,61","9373432,00","9563580,50",...,"18453860,49","19995280,39","18185986,17","18871513,02","18597375,56","17805273,37","17543184,88","18526929,38","22118639,05","2236415402,51"
14,Sergipe,"2780750,11","3676483,16","5051473,61","5046063,36","4741151,56","5401259,63","5521904,44","5238398,50","5187912,19",...,"10313262,56","11404646,48","10741986,60","12278300,58","12264609,05","11454427,82","12060864,70","13003816,54","13321494,41","1215853015,00"
15,Bahia,"21211522,47","28189304,95","34181483,52","39026934,13","42949566,82","47025972,04","47481695,17","46931248,28","44883379,31",...,"84204991,86","83478081,57","80540324,01","81250834,02","86257814,00","85871122,17","79961693,17","81992571,15","98746333,07","9791541570,52"
16,Minas Gerais,"45671659,76","70194037,10","79231336,95","77136537,58","80554440,63","94758522,83","85360064,11","84722528,10","84601757,95",...,"165759955,94","171048093,95","175439696,53","178279152,74","175253226,91","172509435,62","174722161,98","177270694,34","200471045,07","20418737536,66"
17,Espírito Santo,"5456723,98","9102212,86","10249595,97","11253833,56","10198619,17","13364258,29","13035374,08","12588595,77","12727433,30",...,"33474963,98","32364742,01","38569356,14","35748380,19","32030401,25","33674687,78","39642483,39","40243896,20","45490499,45","3405850698,58"
18,Rio de Janeiro,"23025258,52","28394310,93","44567062,94","44054604,82","44911021,15","48056212,24","49872379,35","50912706,60","49270352,76",...,"99331352,01","96339615,99","88305239,94","86995649,35","86776500,97","90416725,95","94179674,42","85583557,95","106837295,81","10337391164,52"
19,São Paulo,"91678473,48","148677526,82","156087269,23","161227125,43","187119397,64","187291126,07","194398399,48","184854516,35","188636359,55",...,"367648996,72","349900969,68","354117254,42","345733068,79","335084865,66","330489045,98","355149525,60","348827130,99","392946147,42","41396604304,13"
20,Paraná,"38266347,46","55384670,52","53801318,85","52460306,69","54419620,71","57811688,48","58094241,83","56982774,90","57549082,26",...,"109720663,59","129529222,48","122702263,26","129647873,97","126859051,02","120037066,76","122122779,12","132622112,72","140264608,52","14681514706,67"
21,Santa Catarina,"16504913,45","25651429,11","26743524,89","27181488,26","26845308,18","29909762,04","30789135,84","31250854,33","30019676,93",...,"61267297,89","65467585,93","71781494,82","69414431,71","68460616,55","70333079,37","71970474,56","74337524,03","81376630,57","7835011163,40"
22,Rio Grande do Sul,"30931325,46","57363420,01","51547794,07","56673338,49","48397733,07","52413429,62","56636376,98","56113054,70","55356224,30",...,"100579287,65","102609965,59","104401019,54","117458292,46","108853890,98","111760506,80","119992419,94","111797400,70","130155185,16","12764391179,92"
23,Mato Grosso do Sul,"5377392,11","7002472,61","8423933,19","8797487,68","9770421,80","10905392,18","10249299,82","9671553,45","10218511,05",...,"18858844,44","19877080,68","19247894,51","19497210,85","22023126,25","19629591,55","21693311,15","24337295,63","25168195,34","2324525096,33"
24,Mato Grosso,"4795299,01","8684882,23","7886243,14","8794109,79","9231645,40","10221763,77","9163314,28","9243148,81","9052354,89",...,"16834650,98","19704915,36","20746227,60","22727405,20","20506039,58","19583803,46","19120141,68","18349376,92","19611032,61","2180119781,15"
25,Goiás,"15310637,29","22258668,68","21442515,75","20921212,45","21615970,67","18270043,87","20540517,13","20650730,67","20868443,56",...,"40606222,82","46229357,10","44889588,33","45529496,23","43037600,45","44147353,21","46127763,88","42742773,93","45592686,49","4973573613,47"
26,Distrito Federal,"4745919,19","7632480,67","9647203,26","11098732,99","12891719,72","12850125,67","12565646,74","13710857,89","13165106,20",...,"25269773,34","26526196,39","20056592,11","20856249,30","20459325,27","22991567,76","23527050,29","22766952,62","31831917,45","2592422853,56"
27,Total,"408424859,23","613174269,21","664043058,38","686662861,42","715803639,49","752181563,64","764990284,76","750608648,28","752962642,15",...,"1484010417,62","1514160823,72","1477904466,14","1489983146,21","1464196395,75","1441199605,05","1513991196,49","1500612299,36","1687562138,38","172481760138,88"
28,Fonte: Ministério da Saúde - Sistema de Infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Notas:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,"Dados referentes aos últimos seis meses, suje...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,"A partir do processamento de junho de 2012, h...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Até maio de 2012 estas informações estão...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,"De junho de 2012 a outubro de 2015, estã...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,"A partir de novembro de 2015, estão disp...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
indices_para_deletar = [28, 29, 30, 31, 32, 33, 34]
dados = dados.drop(indices_para_deletar)

display(dados.tail())

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
23,Mato Grosso do Sul,"5377392,11","7002472,61","8423933,19","8797487,68","9770421,80","10905392,18","10249299,82","9671553,45","10218511,05",...,"18858844,44","19877080,68","19247894,51","19497210,85","22023126,25","19629591,55","21693311,15","24337295,63","25168195,34","2324525096,33"
24,Mato Grosso,"4795299,01","8684882,23","7886243,14","8794109,79","9231645,40","10221763,77","9163314,28","9243148,81","9052354,89",...,"16834650,98","19704915,36","20746227,60","22727405,20","20506039,58","19583803,46","19120141,68","18349376,92","19611032,61","2180119781,15"
25,Goiás,"15310637,29","22258668,68","21442515,75","20921212,45","21615970,67","18270043,87","20540517,13","20650730,67","20868443,56",...,"40606222,82","46229357,10","44889588,33","45529496,23","43037600,45","44147353,21","46127763,88","42742773,93","45592686,49","4973573613,47"
26,Distrito Federal,"4745919,19","7632480,67","9647203,26","11098732,99","12891719,72","12850125,67","12565646,74","13710857,89","13165106,20",...,"25269773,34","26526196,39","20056592,11","20856249,30","20459325,27","22991567,76","23527050,29","22766952,62","31831917,45","2592422853,56"
27,Total,"408424859,23","613174269,21","664043058,38","686662861,42","715803639,49","752181563,64","764990284,76","750608648,28","752962642,15",...,"1484010417,62","1514160823,72","1477904466,14","1489983146,21","1464196395,75","1441199605,05","1513991196,49","1500612299,36","1687562138,38","172481760138,88"

In [ ]:
dados

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"
5,Amapá,"1120973,34","1268740,33","974651,24","1141137,32","866346,18","1440978,95","1426659,48","1475551,38","1651341,43",...,"3253399,45","2946398,44","2416019,23","2203732,04","2218532,26","2566919,60","2802886,34","2817849,31","3188210,98","309860092,59"
6,Tocantins,"3441592,69","4985688,85","6205612,60","4984482,09","5511002,46","4927934,22","5445602,28","5413710,38","5596669,50",...,"9155572,36","8390267,72","8729632,49","7770885,66","527840,46","675277,05","419553,49","319160,87","1357751,33","1020028272,64"
7,Maranhão,"10723506,39","13559679,41","13985142,36","14809416,46","14505727,38","14908091,32","15784899,40","15195312,89","14951277,75",...,"35473489,49","32219037,29","30077152,72","33200778,47","31942670,33","30783403,58","30738750,31","30924484,99","39663677,48","3871069498,04"
8,Piauí,"7985142,43","10079928,25","10298372,45","10775976,33","10398360,88","10528253,88","11040107,92","10549176,40","10899198,97",...,"19908573,27","25663537,49","20230782,72","22389215,72","18911604,50","20883972,79","22689390,32","19400269,01","20018325,75","2280888802,74"
9,Ceará,"15539821,90","25735101,55","28724625,75","30676457,06","30604453,47","31272395,18","30925391,36","27851438,72","30362719,90",...,"56019506,33","61719491,69","56625919,77","59074596,33","56916499,66","50849353,22","52078218,88","53171253,41","62079618,54","6591836650,18"
10,Rio Grande do Norte,"5947814,08","9509755,83","10352238,59","10855108,50","11160168,19","10475071,38","11386349,96","10640817,47","11336030,28",...,"26337808,77","27579658,62","27721340,38","26048003,33","24737052,09","23846816,35","28044464,51","26317613,74","23306498,68","2660122027,15"
11,Paraíba,"10723002,45","11386274,47","12053643,87","12653528,76","12215107,11","12256928,49","12755413,77","12872578,37","12558296,11",...,"27294311,05","23288213,79","19480481,07","19988426,94","18418075,59","18099514,43","19524543,63","21302722,77","25750897,89","2614919044,63"
12,Pernambuco,"14393949,89","24181400,95","29991302,71","34806197,97","32147987,35","32239094,89","32685640,76","35457038,66","33668261,46",...,"74914677,43","77232881,01","71715677,42","66555628,25","78904176,21","70978052,15","83846222,44","75562664,69","83870992,73","8581189975,91"
13,Alagoas,"6243726,32","8376622,16","8408336,22","9090794,82","9338771,45","10068210,08","9887061,61","9373432,00","9563580,50",...,"18453860,49","19995280,39","18185986,17","18871513,02","18597375,56","17805273,37","17543184,88","18526929,38","22118639,05","2236415402,51"
14,Sergipe,"2780750,11","3676483,16","5051473,61","5046063,36","4741151,56","5401259,63","5521904,44","5238398,50","5187912,19",...,"10313262,56","11404646,48","10741986,60","12278300,58","12264609,05","11454427,82","12060864,70","13003816,54","13321494,41","1215853015,00"
15,Bahia,"21211522,47","28189304,95","34181483,52","39026934,13","42949566,82","47025972,04","47481695,17","46931248,28","44883379,31",...,"84204991,86","83478081,57","80540324,01","81250834,02","86257814,00","85871122,17","79961693,17","81992571,15","98746333,07","9791541570,52"
16,Minas Gerais,"45671659,76","70194037,10","79231336,95","77136537,58","80554440,63","94758522,83","85360064,11","84722528,10","84601757,95",...,"165759955,94","171048093,95","175439696,53","178279152,74","175253226,91","172509435,62","174722161,98","177270694,34","200471045,07","20418737536,66"
17,Espírito Santo,"5456723,98","9102212,86","10249595,97","11253833,56","10198619,17","13364258,29","13035374,08","12588595,77","12727433,30",...,"33474963,98","32364742,01","38569356,14","35748380,19","32030401,25","33674687,78","39642483,39","40243896,20","45490499,45","3405850698,58"
18,Rio de Janeiro,"23025258,52","28394310,93","44567062,94","44054604,82","44911021,15","48056212,24","49872379,35","50912706,60","49270352,76",...,"99331352,01","96339615,99","88305239,94","86995649,35","86776500,97","90416725,95","94179674,42","85583557,95","106837295,81","10337391164,52"
19,São Paulo,"91678473,48","148677526,82","156087269,23","161227125,43","187119397,64","187291126,07","194398399,48","184854516,35","188636359,55",...,"367648996,72","349900969,68","354117254,42","345733068,79","335084865,66","330489045,98","355149525,60","348827130,99","392946147,42","41396604304,13"
20,Paraná,"38266347,46","55384670,52","53801318,85","52460306,69","54419620,71","57811688,48","58094241,83","56982774,90","57549082,26",...,"109720663,59","129529222,48","122702263,26","129647873,97","126859051,02","120037066,76","122122779,12","132622112,72","140264608,52","14681514706,67"
21,Santa Catarina,"16504913,45","25651429,11","26743524,89","27181488,26","26845308,18","29909762,04","30789135,84","31250854,33","30019676,93",...,"61267297,89","65467585,93","71781494,82","69414431,71","68460616,55","70333079,37","71970474,56","74337524,03","81376630,57","7835011163,40"
22,Rio Grande do Sul,"30931325,46","57363420,01","51547794,07","56673338,49","48397733,07","52413429,62","56636376,98","56113054,70","55356224,30",...,"100579287,65","102609965,59","104401019,54","117458292,46","108853890,98","111760506,80","119992419,94","111797400,70","130155185,16","12764391179,92"
23,Mato Grosso do Sul,"5377392,11","7002472,61","8423933,19","8797487,68","9770421,80","10905392,18","10249299,82","9671553,45","10218511,05",...,"18858844,44","19877080,68","19247894,51","19497210,85","22023126,25","19629591,55","21693311,15","24337295,63","25168195,34","2324525096,33"
24,Mato Grosso,"4795299,01","8684882,23","7886243,14","8794109,79","9231645,40","10221763,77","9163314,28","9243148,81","9052354,89",...,"16834650,98","19704915,36","20746227,60","22727405,20","20506039,58","19583803,46","19120141,68","18349376,92","19611032,61","2180119781,15"
25,Goiás,"15310637,29","22258668,68","21442515,75","20921212,45","21615970,67","18270043,87","20540517,13","20650730,67","20868443,56",...,"40606222,82","46229357,10","44889588,33","45529496,23","43037600,45","44147353,21","46127763,88","42742773,93","45592686,49","4973573613,47"
26,Distrito Federal,"4745919,19","7632480,67","9647203,26","11098732,99","12891719,72","12850125,67","12565646,74","13710857,89","13165106,20",...,"25269773,34","26526196,39","20056592,11","20856249,30","20459325,27","22991567,76","23527050,29","22766952,62","31831917,45","2592422853,56"
27,Total,"408424859,23","613174269,21","664043058,38","686662861,42","715803639,49","752181563,64","764990284,76","750608648,28","752962642,15",...,"1484010417,62","1514160823,72","1477904466,14","1489983146,21","1464196395,75","1441199605,05","1513991196,49","1500612299,36","1687562138,38","172481760138,88"

###**Escrevendo arquivos CSV**

In [ ]:
dados.to_csv('dados_sus_tratados.csv', index=False)

In [ ]:
dados_tratados = pd.read_csv('/content/dados_sus_tratados.csv')
dados_tratados

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"
5,Amapá,"1120973,34","1268740,33","974651,24","1141137,32","866346,18","1440978,95","1426659,48","1475551,38","1651341,43",...,"3253399,45","2946398,44","2416019,23","2203732,04","2218532,26","2566919,60","2802886,34","2817849,31","3188210,98","309860092,59"
6,Tocantins,"3441592,69","4985688,85","6205612,60","4984482,09","5511002,46","4927934,22","5445602,28","5413710,38","5596669,50",...,"9155572,36","8390267,72","8729632,49","7770885,66","527840,46","675277,05","419553,49","319160,87","1357751,33","1020028272,64"
7,Maranhão,"10723506,39","13559679,41","13985142,36","14809416,46","14505727,38","14908091,32","15784899,40","15195312,89","14951277,75",...,"35473489,49","32219037,29","30077152,72","33200778,47","31942670,33","30783403,58","30738750,31","30924484,99","39663677,48","3871069498,04"
8,Piauí,"7985142,43","10079928,25","10298372,45","10775976,33","10398360,88","10528253,88","11040107,92","10549176,40","10899198,97",...,"19908573,27","25663537,49","20230782,72","22389215,72","18911604,50","20883972,79","22689390,32","19400269,01","20018325,75","2280888802,74"
9,Ceará,"15539821,90","25735101,55","28724625,75","30676457,06","30604453,47","31272395,18","30925391,36","27851438,72","30362719,90",...,"56019506,33","61719491,69","56625919,77","59074596,33","56916499,66","50849353,22","52078218,88","53171253,41","62079618,54","6591836650,18"
10,Rio Grande do Norte,"5947814,08","9509755,83","10352238,59","10855108,50","11160168,19","10475071,38","11386349,96","10640817,47","11336030,28",...,"26337808,77","27579658,62","27721340,38","26048003,33","24737052,09","23846816,35","28044464,51","26317613,74","23306498,68","2660122027,15"
11,Paraíba,"10723002,45","11386274,47","12053643,87","12653528,76","12215107,11","12256928,49","12755413,77","12872578,37","12558296,11",...,"27294311,05","23288213,79","19480481,07","19988426,94","18418075,59","18099514,43","19524543,63","21302722,77","25750897,89","2614919044,63"
12,Pernambuco,"14393949,89","24181400,95","29991302,71","34806197,97","32147987,35","32239094,89","32685640,76","35457038,66","33668261,46",...,"74914677,43","77232881,01","71715677,42","66555628,25","78904176,21","70978052,15","83846222,44","75562664,69","83870992,73","8581189975,91"
13,Alagoas,"6243726,32","8376622,16","8408336,22","9090794,82","9338771,45","10068210,08","9887061,61","9373432,00","9563580,50",...,"18453860,49","19995280,39","18185986,17","18871513,02","18597375,56","17805273,37","17543184,88","18526929,38","22118639,05","2236415402,51"
14,Sergipe,"2780750,11","3676483,16","5051473,61","5046063,36","4741151,56","5401259,63","5521904,44","5238398,50","5187912,19",...,"10313262,56","11404646,48","10741986,60","12278300,58","12264609,05","11454427,82","12060864,70","13003816,54","13321494,41","1215853015,00"
15,Bahia,"21211522,47","28189304,95","34181483,52","39026934,13","42949566,82","47025972,04","47481695,17","46931248,28","44883379,31",...,"84204991,86","83478081,57","80540324,01","81250834,02","86257814,00","85871122,17","79961693,17","81992571,15","98746333,07","9791541570,52"
16,Minas Gerais,"45671659,76","70194037,10","79231336,95","77136537,58","80554440,63","94758522,83","85360064,11","84722528,10","84601757,95",...,"165759955,94","171048093,95","175439696,53","178279152,74","175253226,91","172509435,62","174722161,98","177270694,34","200471045,07","20418737536,66"
17,Espírito Santo,"5456723,98","9102212,86","10249595,97","11253833,56","10198619,17","13364258,29","13035374,08","12588595,77","12727433,30",...,"33474963,98","32364742,01","38569356,14","35748380,19","32030401,25","33674687,78","39642483,39","40243896,20","45490499,45","3405850698,58"
18,Rio de Janeiro,"23025258,52","28394310,93","44567062,94","44054604,82","44911021,15","48056212,24","49872379,35","50912706,60","49270352,76",...,"99331352,01","96339615,99","88305239,94","86995649,35","86776500,97","90416725,95","94179674,42","85583557,95","106837295,81","10337391164,52"
19,São Paulo,"91678473,48","148677526,82","156087269,23","161227125,43","187119397,64","187291126,07","194398399,48","184854516,35","188636359,55",...,"367648996,72","349900969,68","354117254,42","345733068,79","335084865,66","330489045,98","355149525,60","348827130,99","392946147,42","41396604304,13"
20,Paraná,"38266347,46","55384670,52","53801318,85","52460306,69","54419620,71","57811688,48","58094241,83","56982774,90","57549082,26",...,"109720663,59","129529222,48","122702263,26","129647873,97","126859051,02","120037066,76","122122779,12","132622112,72","140264608,52","14681514706,67"
21,Santa Catarina,"16504913,45","25651429,11","26743524,89","27181488,26","26845308,18","29909762,04","30789135,84","31250854,33","30019676,93",...,"61267297,89","65467585,93","71781494,82","69414431,71","68460616,55","70333079,37","71970474,56","74337524,03","81376630,57","7835011163,40"
22,Rio Grande do Sul,"30931325,46","57363420,01","51547794,07","56673338,49","48397733,07","52413429,62","56636376,98","56113054,70","55356224,30",...,"100579287,65","102609965,59","104401019,54","117458292,46","108853890,98","111760506,80","119992419,94","111797400,70","130155185,16","12764391179,92"
23,Mato Grosso do Sul,"5377392,11","7002472,61","8423933,19","8797487,68","9770421,80","10905392,18","10249299,82","9671553,45","10218511,05",...,"18858844,44","19877080,68","19247894,51","19497210,85","22023126,25","19629591,55","21693311,15","24337295,63","25168195,34","2324525096,33"
24,Mato Grosso,"4795299,01","8684882,23","7886243,14","8794109,79","9231645,40","10221763,77","9163314,28","9243148,81","9052354,89",...,"16834650,98","19704915,36","20746227,60","22727405,20","20506039,58","19583803,46","19120141,68","18349376,92","19611032,61","2180119781,15"
25,Goiás,"15310637,29","22258668,68","21442515,75","20921212,45","21615970,67","18270043,87","20540517,13","20650730,67","20868443,56",...,"40606222,82","46229357,10","44889588,33","45529496,23","43037600,45","44147353,21","46127763,88","42742773,93","45592686,49","4973573613,47"
26,Distrito Federal,"4745919,19","7632480,67","9647203,26","11098732,99","12891719,72","12850125,67","12565646,74","13710857,89","13165106,20",...,"25269773,34","26526196,39","20056592,11","20856249,30","20459325,27","22991567,76","23527050,29","22766952,62","31831917,45","2592422853,56"
27,Total,"408424859,23","613174269,21","664043058,38","686662861,42","715803639,49","752181563,64","764990284,76","750608648,28","752962642,15",...,"1484010417,62","1514160823,72","1477904466,14","1489983146,21","1464196395,75","1441199605,05","1513991196,49","1500612299,36","1687562138,38","172481760138,88"

##**2 - Arquivos do Google planilhas**

link da planilha: https://docs.google.com/spreadsheets/d/1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw/edit?usp=sharing

In [ ]:
sheet_id = '1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [ ]:
dados_co2_sheets = pd.read_csv(url)

In [ ]:
dados_co2_sheets

,Country,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),191.745.115,167.681.579,95.957.742,8.472.111,75.545.827,68.467.956,...,29.650.624,259.295.334,18.562.366,146.235.617,172.896.741,149.789.334,131.694.556,1.632.953,159.824.372,159.824.372
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),553.661.955,544.538.649,543.557.223,70.898.423,836.804.405,912.141.485,...,985.522.312,950.695.879,1.036.293.852,1.099.779.111,113.504.405,1.031.811.348,81.330.073,777.674.934,792.137.069,792.137.069
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819.541.634,124.281.022,683.699.826,638.307.036,645.355.189,605.436.253,...,166.942.319,150.324.046,1.533.630.039,1.668.337.371,160.377.515,1.557.664.358,1.788.786.074,1.782.738.948,169.224.832,169.224.832
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521.831.658,723.537.924,69.630.787,6.724.177.518,6.541.578.914,6.733.479.486,...,5.850.886.105,5.944.654.173,5.942.800.412,5.807.127.723,6.026.181.822,6.080.600.282,6.104.133.912,6.362.975.399,6.481.217.432,6.481.217.432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,"Yemen, Rep.",YEM,Middle East & North Africa,CO2 emissions (metric tons per capita),56.703.735,690.937.429,704.793.064,627.104.927,653.255.714,706.080.534,...,963.978.488,858.490.955,1.106.687.715,1.062.211.282,511.361.652,399.363.829,359.621.635,341.068.402,380.633.361,380.633.361
212,South Africa,ZAF,Sub-Saharan Africa,CO2 emissions (metric tons per capita),6.729.798.587,6.424.621.766,6.175.429.944,6.219.193.872,6.215.847.077,6.378.789.568,...,7.869.815.906,8.077.957.969,8.138.264.312,8.212.241.156,7.669.937.662,7.563.739.495,7.641.675.086,7.515.678.605,7.507.736.092,7.507.736.092
213,Zambia,ZMB,Sub-Saharan Africa,CO2 emissions (metric tons per capita),340.929.635,349.232.211,33.722.439,289.956.061,241.269.619,234.153.214,...,217.496.732,27.860.069,284.057.568,304.549.552,312.354.964,325.114.844,404.067.778,445.489.133,380.717.051,380.717.051
214,Zimbabwe,ZWE,Sub-Saharan Africa,CO2 emissions (metric tons per capita),1.585.443.976,1.713.321.439,1.694.415.977,1.539.740.958,1.417.186.242,135.661.892,...,88.488.553,915.734.944,919.824.123,889.104.126,899.769.991,78.544.084,726.297.071,857.411.269,80.297.852,80.297.852
215,NaN,NaN,shhhhhh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
dados_co2_sheets.fillna(0, inplace=True)
dados_co2_sheets

,Country,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),191.745.115,167.681.579,95.957.742,8.472.111,75.545.827,68.467.956,...,29.650.624,259.295.334,18.562.366,146.235.617,172.896.741,149.789.334,131.694.556,1.632.953,159.824.372,159.824.372
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),553.661.955,544.538.649,543.557.223,70.898.423,836.804.405,912.141.485,...,985.522.312,950.695.879,1.036.293.852,1.099.779.111,113.504.405,1.031.811.348,81.330.073,777.674.934,792.137.069,792.137.069
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819.541.634,124.281.022,683.699.826,638.307.036,645.355.189,605.436.253,...,166.942.319,150.324.046,1.533.630.039,1.668.337.371,160.377.515,1.557.664.358,1.788.786.074,1.782.738.948,169.224.832,169.224.832
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521.831.658,723.537.924,69.630.787,6.724.177.518,6.541.578.914,6.733.479.486,...,5.850.886.105,5.944.654.173,5.942.800.412,5.807.127.723,6.026.181.822,6.080.600.282,6.104.133.912,6.362.975.399,6.481.217.432,6.481.217.432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,"Yemen, Rep.",YEM,Middle East & North Africa,CO2 emissions (metric tons per capita),56.703.735,690.937.429,704.793.064,627.104.927,653.255.714,706.080.534,...,963.978.488,858.490.955,1.106.687.715,1.062.211.282,511.361.652,399.363.829,359.621.635,341.068.402,380.633.361,380.633.361
212,South Africa,ZAF,Sub-Saharan Africa,CO2 emissions (metric tons per capita),6.729.798.587,6.424.621.766,6.175.429.944,6.219.193.872,6.215.847.077,6.378.789.568,...,7.869.815.906,8.077.957.969,8.138.264.312,8.212.241.156,7.669.937.662,7.563.739.495,7.641.675.086,7.515.678.605,7.507.736.092,7.507.736.092
213,Zambia,ZMB,Sub-Saharan Africa,CO2 emissions (metric tons per capita),340.929.635,349.232.211,33.722.439,289.956.061,241.269.619,234.153.214,...,217.496.732,27.860.069,284.057.568,304.549.552,312.354.964,325.114.844,404.067.778,445.489.133,380.717.051,380.717.051
214,Zimbabwe,ZWE,Sub-Saharan Africa,CO2 emissions (metric tons per capita),1.585.443.976,1.713.321.439,1.694.415.977,1.539.740.958,1.417.186.242,135.661.892,...,88.488.553,915.734.944,919.824.123,889.104.126,899.769.991,78.544.084,726.297.071,857.411.269,80.297.852,80.297.852
215,0,0,shhhhhh,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
dados_co2_sheets.tail()

,Country,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
211,"Yemen, Rep.",YEM,Middle East & North Africa,CO2 emissions (metric tons per capita),56.703.735,690.937.429,704.793.064,627.104.927,653.255.714,706.080.534,...,963.978.488,858.490.955,1.106.687.715,1.062.211.282,511.361.652,399.363.829,359.621.635,341.068.402,380.633.361,380.633.361
212,South Africa,ZAF,Sub-Saharan Africa,CO2 emissions (metric tons per capita),6.729.798.587,6.424.621.766,6.175.429.944,6.219.193.872,6.215.847.077,6.378.789.568,...,7.869.815.906,8.077.957.969,8.138.264.312,8.212.241.156,7.669.937.662,7.563.739.495,7.641.675.086,7.515.678.605,7.507.736.092,7.507.736.092
213,Zambia,ZMB,Sub-Saharan Africa,CO2 emissions (metric tons per capita),340.929.635,349.232.211,33.722.439,289.956.061,241.269.619,234.153.214,...,217.496.732,27.860.069,284.057.568,304.549.552,312.354.964,325.114.844,404.067.778,445.489.133,380.717.051,380.717.051
214,Zimbabwe,ZWE,Sub-Saharan Africa,CO2 emissions (metric tons per capita),1.585.443.976,1.713.321.439,1.694.415.977,1.539.740.958,1.417.186.242,135.661.892,...,88.488.553,915.734.944,919.824.123,889.104.126,899.769.991,78.544.084,726.297.071,857.411.269,80.297.852,80.297.852
215,0,0,shhhhhh,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

###**Salvando dados do google planilhas no formato CSV**

In [ ]:
dados_co2_sheets.to_csv('dados_co2_sheets.csv', index=False)

In [ ]:
dados_co2_sheets = pd.read_csv('/content/dados_co2_sheets.csv')
dados_co2_sheets

,Country,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),191.745.115,167.681.579,95.957.742,8.472.111,75.545.827,68.467.956,...,29.650.624,259.295.334,18.562.366,146.235.617,172.896.741,149.789.334,131.694.556,1.632.953,159.824.372,159.824.372
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),553.661.955,544.538.649,543.557.223,70.898.423,836.804.405,912.141.485,...,985.522.312,950.695.879,1.036.293.852,1.099.779.111,113.504.405,1.031.811.348,81.330.073,777.674.934,792.137.069,792.137.069
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819.541.634,124.281.022,683.699.826,638.307.036,645.355.189,605.436.253,...,166.942.319,150.324.046,1.533.630.039,1.668.337.371,160.377.515,1.557.664.358,1.788.786.074,1.782.738.948,169.224.832,169.224.832
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521.831.658,723.537.924,69.630.787,6.724.177.518,6.541.578.914,6.733.479.486,...,5.850.886.105,5.944.654.173,5.942.800.412,5.807.127.723,6.026.181.822,6.080.600.282,6.104.133.912,6.362.975.399,6.481.217.432,6.481.217.432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,"Yemen, Rep.",YEM,Middle East & North Africa,CO2 emissions (metric tons per capita),56.703.735,690.937.429,704.793.064,627.104.927,653.255.714,706.080.534,...,963.978.488,858.490.955,1.106.687.715,1.062.211.282,511.361.652,399.363.829,359.621.635,341.068.402,380.633.361,380.633.361
212,South Africa,ZAF,Sub-Saharan Africa,CO2 emissions (metric tons per capita),6.729.798.587,6.424.621.766,6.175.429.944,6.219.193.872,6.215.847.077,6.378.789.568,...,7.869.815.906,8.077.957.969,8.138.264.312,8.212.241.156,7.669.937.662,7.563.739.495,7.641.675.086,7.515.678.605,7.507.736.092,7.507.736.092
213,Zambia,ZMB,Sub-Saharan Africa,CO2 emissions (metric tons per capita),340.929.635,349.232.211,33.722.439,289.956.061,241.269.619,234.153.214,...,217.496.732,27.860.069,284.057.568,304.549.552,312.354.964,325.114.844,404.067.778,445.489.133,380.717.051,380.717.051
214,Zimbabwe,ZWE,Sub-Saharan Africa,CO2 emissions (metric tons per capita),1.585.443.976,1.713.321.439,1.694.415.977,1.539.740.958,1.417.186.242,135.661.892,...,88.488.553,915.734.944,919.824.123,889.104.126,899.769.991,78.544.084,726.297.071,857.411.269,80.297.852,80.297.852
215,0,0,shhhhhh,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

##**3 - Manipulando arquivos JSON**

###**Lendo arquivos JSON**

In [ ]:
import pandas as pd

In [ ]:
url = 'https://jsonplaceholder.typicode.com/users'

In [ ]:
dados_json = pd.read_json(url)
dados_json

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [ ]:
df_normalizado = pd.json_normalize(dados_json['address'])
df_normalizado

,street,suite,city,zipcode,geo.lat,geo.lng
0,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496
1,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618
2,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653
3,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990
4,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342
5,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,71.7478
6,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,21.8984
7,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-120.7677
8,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,-168.8889
9,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,57.2232

In [ ]:
df_normalizado_company = pd.json_normalize(dados_json['company'])
df_normalizado_company

,name,catchPhrase,bs
0,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems
5,Considine-Lockman,Synchronised bottom-line interface,e-enable innovative applications
6,Johns Group,Configurable multimedia task-force,generate enterprise e-tailers
7,Abernathy Group,Implemented secondary concept,e-enable extensible e-tailers
8,Yost and Sons,Switchable contextually-based project,aggregate real-time technologies
9,Hoeger LLC,Centralized empowering task-force,target end-to-end models

##**4 - Lendo dados em HTML**

In [ ]:
import pandas as pd

In [ ]:
url = 'https://pt.wikipedia.org/wiki/Lista_de_pa%C3%ADses_por_popula%C3%A7%C3%A3o'

In [ ]:
dados_html = pd.read_html(url)

In [ ]:
dados_html

[     Unnamed: 0 Posição    País (ou território dependente) Estimativa da ONU  \
 0           NaN       1                              Índia     1 417 492 000
 1           NaN       2                      China[nota 1]     1.407.934.000
 2           NaN       3                     Estados Unidos       342.181.000
 3           NaN       4                          Indonésia       285.783.000
 4           NaN       5                          Paquistão       256 204 000
 ..          ...     ...                                ...               ...
 245         NaN       –     Ilha de Ascensão (Reino Unido)             1 100
 246         NaN     195                           Vaticano               879
 247         NaN       –  Ilhas Cocos (Keeling) (Austrália)               605
 248         NaN       –     Tristão da Cunha (Reino Unido)               264
 249         NaN       –       Ilhas Pitcairn (Reino Unido)                67

     Crescimento desde a última estimativa      Estimativa Oficial
 0                             -12 692 000      Estimativa oficial
 1                              -1 390 000           Censo oficial
 2                              -2 084 000           Censo oficial
 3                              +3 337 000      Estimativa oficial
 4                              +6 567 000      Estimativa oficial
 ..                                    ...                     ...
 245                                   NaN  Estimativa oficial[10]
 246                                   NaN      Estimativa oficial
 247                                   NaN      Estimativa oficial
 248                                   NaN  Estimativa oficial[11]
 249                                   NaN      Estimativa oficial

 [250 rows x 6 columns],
    vdeListas de países                              vdeListas de países.1
 0             Ambiente  Bem-estar sustentável Desempenho ambiental Emi...
 1              Códigos  COI FIFA FIPS ISO Prefixo naval Telefônicos TL...
 2           Demografia  Esperança de vida Fecundidade Imigrantes Morta...
 3             Economia  Capacidade Nacional Capital Humano Competitivi...
 4              Consumo  Bebidas Cerveja Idade legal Cannabis Adultos C...
 5              Energia  Eletricidade Produção Renovável Gás Natural Ex...
 6                  PIB  Crescimento Real PIB Nominal per capita PIB po...
 7             Produção  Alumínio Antimônio Bauxita Bismuto Carvão Rese...
 8           Transporte  Aeroportos Automóveis per capita Produzidos He...
 9            Geografia  Área Capital Continente Fronteiras Terrestres ...
 10         Militarismo  Armas de fogo Artilharia Batalhas Blindados de...
 11              Órgãos  BRICS Commonwealth COI CPLP Estatuto de Roma F...
 12            Política  Chefes de Estado e de Governo Constituições Co...
 13               Saúde  Antidepressivos HIV/AIDS em adultos Obesidade ...
 14            Símbolos  Emblemas Etimologia Gentílicos Grafias múltipl...
 15           Sociedade  Aborto Arranha-céus e estruturas Data de funda...,
             0                                                  1
 0     Consumo  Bebidas Cerveja Idade legal Cannabis Adultos C...
 1     Energia  Eletricidade Produção Renovável Gás Natural Ex...
 2         PIB  Crescimento Real PIB Nominal per capita PIB po...
 3    Produção  Alumínio Antimônio Bauxita Bismuto Carvão Rese...
 4  Transporte  Aeroportos Automóveis per capita Produzidos He...]

In [ ]:
type(dados_html)

list

In [ ]:
len(dados_html)

3

In [ ]:
dados_avaliacao = dados_html[0]
dados_avaliacao

,Unnamed: 0,Posição,País (ou território dependente),Estimativa da ONU,Crescimento desde a última estimativa,Estimativa Oficial
0,NaN,1,Índia,1 417 492 000,-12 692 000,Estimativa oficial
1,NaN,2,China[nota 1],1.407.934.000,-1 390 000,Censo oficial
2,NaN,3,Estados Unidos,342.181.000,-2 084 000,Censo oficial
3,NaN,4,Indonésia,285.783.000,+3 337 000,Estimativa oficial
4,NaN,5,Paquistão,256 204 000,+6 567 000,Estimativa oficial
...,...,...,...,...,...,...
245,NaN,–,Ilha de Ascensão (Reino Unido),1 100,NaN,Estimativa oficial[10]
246,NaN,195,Vaticano,879,NaN,Estimativa oficial
247,NaN,–,Ilhas Cocos (Keeling) (Austrália),605,NaN,Estimativa oficial
248,NaN,–,Tristão da Cunha (Reino Unido),264,NaN,Estimativa oficial[11]
249,NaN,–,Ilhas Pitcairn (Reino Unido),67,NaN,Estimativa oficial

In [ ]:
dados_avaliacao = dados_avaliacao.drop('Unnamed: 0', axis=1)
display(dados_avaliacao.head())

,Posição,País (ou território dependente),Estimativa da ONU,Crescimento desde a última estimativa,Estimativa Oficial
0,1,Índia,1 417 492 000,-12 692 000,Estimativa oficial
1,2,China[nota 1],1.407.934.000,-1 390 000,Censo oficial
2,3,Estados Unidos,342.181.000,-2 084 000,Censo oficial
3,4,Indonésia,285.783.000,+3 337 000,Estimativa oficial
4,5,Paquistão,256 204 000,+6 567 000,Estimativa oficial

###**Escrevendo arquivos HTML**

In [ ]:
dados_avaliacao.to_html('dados_avaliacao.html')

In [ ]:
pd.read_html('/content/dados_avaliacao.html')

[     Unnamed: 0 PosiÃ§Ã£o   PaÃ­s (ou territÃ³rio dependente)  \
 0             0         1                              Ãndia
 1             1         2                       China[nota 1]
 2             2         3                      Estados Unidos
 3             3         4                          IndonÃ©sia
 4             4         5                          PaquistÃ£o
 ..          ...       ...                                 ...
 245         245       â     Ilha de AscensÃ£o (Reino Unido)
 246         246       195                            Vaticano
 247         247       â  Ilhas Cocos (Keeling) (AustrÃ¡lia)
 248         248       â     TristÃ£o da Cunha (Reino Unido)
 249         249       â        Ilhas Pitcairn (Reino Unido)

     Estimativa da ONU Crescimento desde a Ãºltima estimativa  \
 0       1 417 492 000                            -12 692 000
 1       1.407.934.000                             -1 390 000
 2         342.181.000                             -2 084 000
 3         285.783.000                             +3 337 000
 4         256 204 000                             +6 567 000
 ..                ...                                    ...
 245             1 100                                    NaN
 246               879                                    NaN
 247               605                                    NaN
 248               264                                    NaN
 249                67                                    NaN

          Estimativa Oficial
 0        Estimativa oficial
 1             Censo oficial
 2             Censo oficial
 3        Estimativa oficial
 4        Estimativa oficial
 ..                      ...
 245  Estimativa oficial[10]
 246      Estimativa oficial
 247      Estimativa oficial
 248  Estimativa oficial[11]
 249      Estimativa oficial

 [250 rows x 6 columns]]

In [ ]:
dados_avaliacao.to_csv('dados_avaliacao.csv', index=False)

In [ ]:
dados_avaliacao = pd.read_csv('/content/dados_avaliacao.csv')
dados_avaliacao

,Posição,País (ou território dependente),Estimativa da ONU,Crescimento desde a última estimativa,Estimativa Oficial
0,1,Índia,1 417 492 000,-12 692 000,Estimativa oficial
1,2,China[nota 1],1.407.934.000,-1 390 000,Censo oficial
2,3,Estados Unidos,342.181.000,-2 084 000,Censo oficial
3,4,Indonésia,285.783.000,+3 337 000,Estimativa oficial
4,5,Paquistão,256 204 000,+6 567 000,Estimativa oficial
...,...,...,...,...,...
245,–,Ilha de Ascensão (Reino Unido),1 100,NaN,Estimativa oficial[10]
246,195,Vaticano,879,NaN,Estimativa oficial
247,–,Ilhas Cocos (Keeling) (Austrália),605,NaN,Estimativa oficial
248,–,Tristão da Cunha (Reino Unido),264,NaN,Estimativa oficial[11]
249,–,Ilhas Pitcairn (Reino Unido),67,NaN,Estimativa oficial

##**5 - Trabalhando com banco de dados**

###**Criando um banco de dados local**

In [ ]:
import sqlalchemy

In [ ]:
from sqlalchemy import create_engine, MetaData, Table, inspect

In [ ]:
engine = create_engine('sqlite:///:memory:')

###**Escrevendo em um banco de dados**

In [ ]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'

In [ ]:
dados_banco = pd.read_csv(url)
dados_banco

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [ ]:
dados_banco.head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [ ]:
dados_banco.to_sql('clientes', engine, index=False)

438463

In [ ]:
inspector = inspect(engine)

In [ ]:
print(inspector.get_table_names())

['clientes']

In [ ]:
query = 'SELECT * FROM clientes'

In [ ]:
pd.read_sql(query, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [ ]:
from sqlalchemy import text

In [ ]:
query = 'DELETE FROM clientes WHERE ID_Cliente=5008809'
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()

In [ ]:
pd.read_sql_table('clientes', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [ ]:
query = 'UPDATE clientes SET Rendimento_anual="300000" WHERE ID_Cliente=6840104'
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()

In [ ]:
pd.read_sql_table('clientes', engine).tail()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
438457,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,300000.0,0,Casa/apartamento próprio
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [ ]:
query = """
INSERT INTO clientes (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia)
VALUES (6850985, 33, 'Doutorado', 'Solteiro', 1, 'Empregado', 'TI', 2, 290000, 0, 'Casa/apartamento próprio');
"""

with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()

In [ ]:
pd.read_sql_table('clientes', engine).tail()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio
438462,6850985,33,Doutorado,Solteiro,1,Empregado,TI,2,290000.0,0,Casa/apartamento próprio